# JUPYTER BOOK CONFIG
title: "Pose2Behav — Course"
author: "Lizbeth Mondragón"

logo: assets/logo_mouse_camera.png
favicon: assets/logo_mouse_camera.png
# Repo buttons in the top bar
repository:
  url: https://github.com/LizbethMG-Teaching/pose2behav-book
  branch: main
  path_to_book: .

html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true

parse:
  myst_enable_extensions:
    - colon_fence      # needed for callouts and directives
    - dollarmath       # $inline$ and $$block$$ math
    - linkify          # auto-detect bare links
    - substitution     # simple text substitutions (optional)
    - deflist          # definition lists (optional)
    - tasklist         # [ ] task checkboxes

# Don’t execute notebooks during build (you can change later)
execute:
  execute_notebooks: "off"
